// Generated by CoffeeScript 1.10.0
(function() {
  var callsites, fs, path;

  callsites = require('callsites');

  fs = require('fs');

  path = require('path');

  module.exports = function(id) {
    var callee, create, filePath, info, oldAngular, ref, stack;
    filePath = null;
    if ((ref = id.charAt(0)) === '.' || ref === '/') {
      stack = callsites();
      callee = stack[1].getFileName();
      callee = callee.split('/');
      callee.pop();
      callee = callee.join('/');
      filePath = path.resolve(callee, id);
    } else {
      filePath = id;
    }
    oldAngular = global.angular;
    info = {};
    create = function(type) {
      return function(name, value) {
        info.type = 'controller';
        info.name = name;
        return info.value = value;
      };
    };
    global.angular = {
      module: function(name) {
        info.module = name;
        return global.angular;
      },
      controller: create('controller'),
      service: create('service'),
      value: create('value'),
      constant: create('constant'),
      factory: create('factory'),
      provider: create('provider')
    };
    require(filePath);
    global.angular = oldAngular;
    if (global.angular === void 0) {
      delete global.angular;
    }
    return info;
  };

}).call(this);
